services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8080/api/v1
    depends_on:
      - backend
    networks:
      - fire-network
    image: osnola/fire-frontend:latest

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PYTHON_PATH=python3
      - PORT=8080
    networks:
      - fire-network
    image: osnola/fire-backend:latest

networks:
  fire-network:
    driver: bridge
